config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'blog', to: 'pages#blog'
  get 'professional', to: 'pages#professional'
  get 'conditions' , to: 'pages#conditions'
  get 'privacy' , to: 'pages#privacy'
  get 'cookies', to: 'pages#cookies'
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end 

	def home
	end

	def blog
	end
	
	def professional 
	end 
	
	def conditions
	end 
	
	def privacy 
	end 
	
	def cookies
	end 

	def contact
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!-- application.html.erb -->
<head>
  <!-- ... -->

      <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />


    <script src="https://kit.fontawesome.com/ad9ced8bb3.js" crossorigin="anonymous"></script>

  <%= favicon_link_tag %>
  <title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body>

  	<%= render 'shared/navbar' %>

    <%= yield %>

    
    <a class="top-link hide" href="" id="js-top">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 6"><path d="M12 6H0l6-6z"/></svg>
  <span class="screen-reader-text">Back to top</span>
</a>

<script>// Set a variable for our button element.
const scrollToTopButton = document.getElementById('js-top');

// Let's set up a function that shows our scroll-to-top button if we scroll beyond the height of the initial window.
const scrollFunc = () => {
  // Get the current scroll value
  let y = window.scrollY;
  
  // If the scroll value is greater than the window height, let's add a class to the scroll-to-top button to show it!
  if (y > 0) {
    scrollToTopButton.className = "top-link show";
  } else {
    scrollToTopButton.className = "top-link hide";
  }
};

window.addEventListener("scroll", scrollFunc);

const scrollToTop = () => {
  // Let's set a variable for the number of pixels we are from the top of the document.
  const c = document.documentElement.scrollTop || document.body.scrollTop;
  
  // If that number is greater than 0, we'll scroll back to 0, or the top of the document.
  // We'll also animate that scroll with requestAnimationFrame:
  // https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame
  if (c > 0) {
    window.requestAnimationFrame(scrollToTop);
    // ScrollTo takes an x and a y coordinate.
    // Increase the '10' value to get a smoother/slower scroll!
    window.scrollTo(0, c - c / 10);
  }
};

// When the button is clicked, run our ScrolltoTop function above!
scrollToTopButton.onclick = function(e) {
  e.preventDefault();
  scrollToTop();
}</script>

  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>


     <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<section class="section-a">
  <div class="container">
    <div>
      <h1>About us</h1><br>
      <p>
        Send money abroad the easy way, 
        with rates up to 9 x cheaper than banks. 
      </p><br><br><br>
    </div>
    <img src="https://i.ibb.co/WkLYPsN/Untitled-Artwork-17.png" />
  </div>
</section>



<div class="cardsh">
    <div class="cards">
        <div class="card card1">
            <div class="container">
                <img src="https://i.ibb.co/CKDWndj/Untitled-Artwork-27.png" alt="las vegas">
            </div>
            <div class="details">
                <h3>KiyanPay Multi-Currency Cards</h3>
                <p>Soon you'll be able to take your virtual money with you and use it wherever you go. With our new multi-currency cards to launch later this year, you will be able to use your money to purchase or withdraw from ATM's around the world.</p>
            </div>
        </div>
        <div class="card card2">
            <div class="container">
                <img src="https://i.ibb.co/N96BYhC/Untitled-Artwork-28.png" alt="New York">
            </div>
            <div class="details">
                <h3>We are making banking Social</h3>
                <p>It's about time, isn't it? Dealing with money can be much more than a boring necessity. Stay tuned!<br><br><br><br><br></p>
            </div>
        </div>
        <div class="card card3">
            <div class="container">
                <img src="https://i.ibb.co/1nJfGQJ/Untitled-Artwork-29.png" alt="Singapore">
            </div>
            <div class="details">
                <h3>Money Transfer Done Right</h3>
                <p>Send money abroad the easy way, with rates up to 9 x cheaper than banks. You will soon have access to a growing list of currencies directly from your KiyanPay account.<br><br><br></p>
            </div>
        </div>
        <div class="card card1">
            <div class="container">
                <img src="https://i.ibb.co/nw1csvg/Untitled-Artwork-31.png" alt="las vegas">
            </div>
            <div class="details">
                <h3>KiyanPay Multi-Currency Cards</h3>
                <p>Soon you'll be able to take your virtual money with you and use it wherever you go. With our new multi-currency cards to launch later this year, you will be able to use your money to purchase or withdraw from ATM's around the world.</p>
            </div>
        </div>
        <div class="card card1">
            <div class="container">
                <img src="https://i.ibb.co/drw2xmK/Untitled-Artwork-32.png" alt="las vegas">
            </div>
            <div class="details">
                <h3>KiyanPay Multi-Currency Cards</h3>
                <p>Soon you'll be able to take your virtual money with you and use it wherever you go. With our new multi-currency cards to launch later this year, you will be able to use your money to purchase or withdraw from ATM's around the world.</p>
            </div>
        </div>
        <div class="card card1">
            <div class="container">
                <img src="https://i.ibb.co/4J1tJ9N/Untitled-Artwork-33.png" alt="las vegas">
            </div>
            <div class="details">
                <h3>KiyanPay Multi-Currency Cards</h3>
                <p>Soon you'll be able to take your virtual money with you and use it wherever you go. With our new multi-currency cards to launch later this year, you will be able to use your money to purchase or withdraw from ATM's around the world.</p>
            </div>
        </div>
    </div>
</div>


<!-- <section id="about" class="section-d">
  <div class="viewport">
    <div class="cards">
  
      <div class="card">
        <div class="card_img card1">
          <img src="https://i.ibb.co/d2YK8bc/Untitled-Artwork-2.png" />
        </div>
        <h3>AMAZING FLUO</h3>
        <div class="line">
        </div>
        <p> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.  </p>  
      </div>
      <div class="card">
        <div class="card_img card2">
          <img src="https://i.ibb.co/Qd3jMyf/Untitled-Artwork-9.png" />
        </div>
        <h3>TITLE HERE</h3>
          <div class="line">
        </div>
        <p> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
      </div>
      <div class="card">
        <div class="card_img card3">
          <img src="https://i.ibb.co/ZW9twLk/Untitled-Artwork-4.png" />
        </div>
        <h3>TITLE HERE</h3>
        <div class="line">
        </div>
        <p>Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
      </div>
      <div class="card">
        <div class="card_img card4">
        <img src="https://i.ibb.co/QHJn0vW/Untitled-Artwork-21.png" />
      </div>
      <h3>TITLE HERE</h3>
      <div class="line">
      </div>
      <p>voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</div>
      <div class="card">
        <div class="card_img card5">
          <img src="https://i.ibb.co/W6yddwk/Untitled-Artwork-5.png" />
        </div>
        <h3>TITLE HERE</h3>
        <div class="line">
        </div>
        <p> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi.</p>
      </div>
      <div class="card">
        <div class="card_img card6">
          <img src="https://i.ibb.co/10tDwJR/Untitled-Artwork-7.png" />
        </div>
        <h3>TITLE HERE</h3>
        <div class="line">
        </div>
        <p> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.  </p>
      </div>
    </div>
  </div>
</section> -->

<!--      <section class="section-b">
      <div class="overlay">
        	<div class="min2">
        		<h1>Always Thinking ahead</h1>
          		<img src="https://i.ibb.co/5B9bRpq/Untitled-Artwork-10.png" alt="" />
      		</div>
      </div>      
    </section> -->

app/views/pages/contact.html.erb
<div class="light-green">
  <div class="container-2">
      <h2>Here for you</h2>
      <div class="section-l-inner">
        <p>Send us a message and we will come back to you in 24 hours.
        </p><br><br>
      </div>
  </div>  
</div> 

<div class="container-fluid contact" id="contact">
  <div class="container">
    <form>
      <h2>Contact Us</h2>
      <input type="text" placeholder="Name" id="name" name="name" class="full-half">
      <input type="email" placeholder="Email" id="email" name="email" class="full-half">
      <input type="text" placeholder="Subject" id="subject" name="subject">
      <textarea placeholder="Message" id="message" name="message"></textarea>
      <input type="submit" value="Send">
    </form>
  </div>
</div>

app/views/pages/home.html.erb
  <!-- Showcase -->
<section class="section-a">
  <div class="container-1">
    <div>
      <div class="slide-left">
      <h1>Banking <br>For All</h1>
      <p>
        Open a free bank account in minutes. <br>No hidden fees, no fuss. 
        <br>Just pure, straightforward banking.
      </p><br><br>
             <a href="https://gate.kiyanpay.com/signup" class="brk-btn">JOIN US TODAY</a>
      </div>
    </div>
    <div class="right-side">
      <img src="https://i.ibb.co/SmnzHkD/Untitled-Artwork-35.png" class="floating" />
    </div>
  </div>
</section>

    <!-- Large Text -->
<section id="about" class="section-c">
  <div class="container-2">
    <div class="float-l">
      <img src="https://i.ibb.co/RBHYFhm/Untitled-Artwork-37.png" class="floating" />
    </div>
    <div class="section-b-inner py-5"><br><br>
      <h2>As simple as it gets</h2>
      <p>We’ve put together all the essential features you really need from a bank into one easy-to-use platform, and removed everything else. No distractions. Because managing your finances should be as simple as possible, but no simpler!
      </p>
    </div>
    <div class="float-r">
      <img src="https://i.ibb.co/88DwvDy/Untitled-Artwork-36.png" class="floating" />
    </div>
  </div>   
</section>


<div class="cardsh">
    <div class="cards">
        <div class="card card1">
            <div class="container">
                <img src="https://i.ibb.co/SJWFCjh/Untitled-Artwork-24.png" alt="las vegas">
            </div>
            <div class="details">
                <h3>Quick Verification</h3>
                <p>We have a secure, fully automated verification process that gets your account ready in minutes, so you can start banking with your new account.<br></p>
            </div>
        </div>
        <div class="card card2">
            <div class="container">
                <img src="https://i.ibb.co/K5TdrjZ/Untitled-Artwork-15.png" alt="New York">
            </div>
            <div class="details">
                <h3>Fully Protected</h3>
                <p>We're signed up to The Financial Services Compensation Scheme (FSCS), which mean your money is protected up to a value of £85,000.</p>
            </div>
        </div>
        <div class="card card3">
            <div class="container">
                <img src="https://i.ibb.co/j5SV3gz/Untitled-Artwork-25.png" alt="Singapore">
            </div>
            <div class="details">
                <h3>Easy Transfers</h3>
                <p>Send money to those that matter to you with a few clicks. We've made transfer process as easy as possible for you.<br><br></p>
            </div>
        </div>
    </div>
</div>


<section class="section-a">
  <div class="container-3">
    <div class="left-s">
      <img src="https://i.ibb.co/CnZWTNV/Untitled-Artwork-16-copy.png" class="floating" />
    </div>
    <div>
      <h1>Centred Around You</h1><br>
      <p>
        Have you ever felt like your bank talks down to you? Same! We know how painful it is to deal with high-street banks. They are slow, unresponsive, and endlessly suspicious. We are here to change that. We've built a bank that works for you. And we really mean it! With Kiyanpay, you are always in the centre and our friendly team are here to serve.
      </p><br><br><br>
      </div>
    <div class="right-s">
      <img src="https://i.ibb.co/b6KmVCH/Untitled-Artwork-16.png" class="floating" />
    </div>
  </div>
</section>



<div class="container-end">
<section class="section-a">
  <div class="container">
    <div>
      <h1>Changing <br>The Way <br>We Bank</h1><br>
      <p>
        We are a creative banking challenger with an eye to the future. We have a lot of exciting, useful features packed and ready to go live soon, and we are always looking for new ways to innovate and revolutionise how we make use of our money. Here are some exciting features in the pipeline.
      </p><br><br><br>
    </div>
    <div class="padd">
      <img src="https://i.ibb.co/98TZJwt/Untitled-Artwork-34.png" class="floating" />
    </div>
  </div>
</section>


  <div class="blog-card">
    <div class="meta">
      <div class="photo" style="background-image: url(https://i.ibb.co/p1mWmpK/Untitled-Artwork-26.png)"></div>
    </div>
    <div class="description">
      <h1>KiyanPay Multi-Currency Cards</h1>
      <p> Soon you'll be able to take your virtual money with you and use it wherever you go. With our new multi-currency cards to launch later this year, you will be able to use your money to purchase or withdraw from ATM's around the world.</p>
    </div>
  </div>
  <div class="blog-card alt">
    <div class="meta">
      <div class="photo" style="background-image: url(https://i.ibb.co/qgnc8H4/Untitled-Artwork-23.png)"></div>
    </div>
    <div class="description">
      <h1>We are making banking Social</h1>
      <p>It's about time, isn't it? Dealing with money can be much more than a boring necessity. Stay tuned!</p>
    </div>
  </div>
  <div class="blog-card">
    <div class="meta">
      <div class="photo" style="background-image: url(https://i.ibb.co/hKhk9WZ/Untitled-Artwork-30.png)"></div>
    </div>
    <div class="description">
      <h1>Money Transfer Done Right</h1>
      <p> Send money abroad the easy way, with rates up to 9 x cheaper than banks. You will soon have access to a growing list of currencies directly from your KiyanPay account.</p>
    </div>
  </div>

<!-- <div class="cardshb">
    <div class="cards">
        <div class="card card1">
            <div class="container">
                <img src="https://i.ibb.co/p1mWmpK/Untitled-Artwork-26.png" alt="las vegas">
            </div>
            <div class="details">
                <h3>KiyanPay Multi-Currency Cards</h3>
                <p>Soon you'll be able to take your virtual money with you and use it wherever you go. With our new multi-currency cards to launch later this year, you will be able to use your money to purchase or withdraw from ATM's around the world.</p>
            </div>
        </div>
        <div class="card card2">
            <div class="container">
                <img src="https://i.ibb.co/qgnc8H4/Untitled-Artwork-23.png" alt="New York">
            </div>
            <div class="details">
                <h3>We are making banking Social</h3>
                <p>It's about time, isn't it? Dealing with money can be much more than a boring necessity. Stay tuned!<br><br><br><br><br></p>
            </div>
        </div>
        <div class="card card3">
            <div class="container">
                <img src="https://i.ibb.co/hKhk9WZ/Untitled-Artwork-30.png" alt="Singapore">
            </div>
            <div class="details">
                <h3>Money Transfer Done Right</h3>
                <p>Send money abroad the easy way, with rates up to 9 x cheaper than banks. You will soon have access to a growing list of currencies directly from your KiyanPay account.<br><br><br></p>
            </div>
        </div>
    </div>
</div> -->
</div>


  <section class="container-5">
    <div class="slider">
      <div class="slide slide-1">
        <div class="slide-text">
          <p class="testimonial-text">
            “ The onboarding took 5 minutes, literally! I can't believe I have created an actual, functioning bank account so fast. Everything is so simple. It has all that I want from a bank, and nothing more. ”
          </p>
          <p class="author-text">Celeste Morel
            <span>Psychology student and tech enthusiast</span></p>
        </div>
        <div class="slide-img">
          <img src="https://i.ibb.co/2qbf0TX/doctor.png" alt="img">
        </div>
      </div>
      <div class="slide slide-2">
        <div class="slide-text">
          <p class="testimonial-text">
            “ It's about time banks actually worked for you, not the other way around. I like the benefits that I get as a business owner from Kiyanpay, but I also love how I'm treated as a customer: with respect and dignity. That's not the attitude I've seen from high-street banks in a long long time. ”
          </p>
          <p class="author-text">Ahmed Farooqi
            <span>Coffee shop owner in London</span></p>
        </div>
        <div class="slide-img">
          <img src="https://i.ibb.co/jMbpWHH/father.png" alt="img">
        </div>
      </div>
      <div class="slide slide-3">
        <div class="slide-text">
          <p class="testimonial-text">
            “ No other bank trusted me when I first came into the UK. They make me feel like I don't belong here. Kiyanpay, however, did things differently, to say the least. Their trust in me made me trust them more than any other bank.  ”
          </p>
          <p class="author-text">Sam Cortez
            <span>Recently chose UK as his family's new home</span></p>
        </div>
        <div class="slide-img">
          <img src="https://i.ibb.co/dmcx6m5/businessman.png" alt="img">
        </div>
      </div>
      <div class="buttons">
        <div class="next"></div>
        <div class="prev"></div>
      </div>
    </div>
  </section>
  
<script>
  const next = document.querySelector('.next');
const prev = document.querySelector('.prev');
const slides = document.querySelectorAll('.slide');

let index = 0;
display(index);
function display (index) {
  slides.forEach((slide) => {
    slide.style.display = 'none';
  });
  slides[index].style.display = 'flex';
}

function nextSlide () {
  index++;
  if (index > slides.length - 1) {
    index = 0;
  }
  display(index);
}
function prevSlide () {
  index--;
  if (index < 0) {
    index = slides.length - 1;
  }
  display(index);
}

next.addEventListener('click', nextSlide);
prev.addEventListener('click', prevSlide);
</script>

  <script>
    const next = document.querySelector('.next');
const prev = document.querySelector('.prev');
const slides = document.querySelectorAll('.slide');

let index = 0;
display(index);
function display (index) {
  slides.forEach((slide) => {
    slide.style.display = 'none';
  });
  slides[index].style.display = 'flex';
}

function nextSlide () {
  index++;
  if (index > slides.length - 1) {
    index = 0;
  }
  display(index);
}
function prevSlide () {
  index--;
  if (index < 0) {
    index = slides.length - 1;
  }
  display(index);
}

next.addEventListener('click', nextSlide);
prev.addEventListener('click', prevSlide);
  </script>

  <!-- Very important to make jquery work -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<!-- Cookies stay at bottom -->
<div class="cookie-container">
  <p>
    We use cookies in this website to give you the best experience on our
    site and show you relevant ads. To find out more, read our
    <%= link_to"Privacy Policy", privacy_path%>.
  </p>
  <button class="cookie-btn">
    Ok
  </button>
</div>


<script>

const cookieContainer = document.querySelector(".cookie-container");
const cookieButton = document.querySelector(".cookie-btn");

cookieButton.addEventListener("click", () => {
  cookieContainer.classList.remove("active");
  localStorage.setItem("cookieBannerDisplayed", "true");
});

setTimeout(() => {
  if (!localStorage.getItem("cookieBannerDisplayed")) {
    cookieContainer.classList.add("active");
  }
}, 2000);
</script>

app/views/pages/professional.html.erb
<section class="section-a">
  <div class="container">
    <div>
      <div class="text-down">
        <h1>A Business Account You Deserve</h1><br>
      <p>
        Sign up your business for a Kiyanpay account today and benefit from our many invoicing . Even if your business is just you, Kiyanpay can get you a business account in minutes and help you grow.
      </p><br><br>
        <a href="https://gate.kiyanpay.com/signup" class="brk-btn">START TODAY</a>
      </div>
    </div>
    <div class="padd">
      <img src="https://i.ibb.co/h9nB1tX/Untitled-Artwork-22.png" class="floating" />
    </div>
  </div>
</section>

<div class="container-green">
  <h2>Scale Your Business Fast</h2>
  <div class="blog-card">
    <div class="meta">
      <div class="photo" style="background-image: url(https://i.ibb.co/kKtqW3g/Business-team-working-on-a-new-business-plan-with-modern-digital-computer-Top-view-shot.jpg)"></div>
    </div>
    <div class="description">
      <h1>Pay People & Employees</h1>
      <p> Make quick and easy payments to those important to your business.</p>
    </div>
  </div>
  <div class="blog-card">
    <div class="meta">
      <div class="photo" style="background-image: url(https://i.ibb.co/YBYn0BQ/Happy-young-busiensswoman-discussing-at-the-meeting-with-his-colleague.jpg)"></div>
    </div>
    <div class="description">
      <h1>Keep Suppliers Happy</h1>
      <p>Give your contractors and suppliers the confidence they need to help you grow.</p>
    </div>
  </div>
  <div class="blog-card">
    <div class="meta">
      <div class="photo" style="background-image: url(https://i.ibb.co/sHS5LyD/man-with-a-shopping-bag-looking-at-the-screen-of-his-smartphone-concept-of-health-protection.jpg)"></div>
    </div>
    <div class="description">
      <h1>Get Real-Time Notifications</h1>
      <p> Keep on top of your account's ongoing activities with our smart notifications.</p>
    </div>
  </div>
</div>


<section id="about" class="section-c">
  <div class="container-2">
    <div class="float-l">
      <img src="https://i.ibb.co/RBHYFhm/Untitled-Artwork-37.png" class="floating" />
    </div>
    <div class="section-b-inner py-5"><br><br>
      <h2>Committed to Small Businesses</h2>
      <p>We’re here for the small businesses. The upstarts, the growth-focused startups and the brick-and-mortar shops. Find out how KiyanPay can help you grow to your full potential.
      </p><br><br>
      <a href="https://gate.kiyanpay.com/signup" class="brk-btn">START TODAY</a>
    </div>
    <div class="float-r">
      <img src="https://i.ibb.co/88DwvDy/Untitled-Artwork-36.png" class="floating" />
    </div>
  </div>   
</section>

app/views/shared/_footer.html.erb
 <!-- Site footer -->
<!-- <footer class="first-footer">
   <div class="container">
   </div>
</footer> -->

    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6></h6>
            <p class="text-justify"><img src="https://i.ibb.co/WxwHJq0/FCA-logo-2.png" alt="" /></p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><%= link_to"About us", about_path%></li>
              <li><%= link_to"Privacy Policy", privacy_path%></li>
              <li><%= link_to"Terms & Conditions", conditions_path%></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Address</h6>
            <ul class="footer-links">
              <li>40 Gracechurch Street</li>
              <li>EC3V 0BT</li>
              <li>London, UK</li>
            </ul><br>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-10 col-sm-6 col-xs-12"><br>
            <p class="copyright-text">KiyanPay is registered by the Financial Conduct Authority under money transfer and payment services Ref No: 814005 and it is licensed, regulated by HMRC as a Money Service Business (MSB) License No.XRML00000131603.</a>
            </p>
          </div>

          <div class="col-md-2 col-sm-6 col-xs-12">
            <ul class="social-icons"><br>
              <li><a class="facebook" href="https://www.facebook.com/kiyanpayexchange"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="https://twitter.com/kiyanpay"><i class="fa fa-twitter"></i></a></li>
              <li><a class="instagram" href="https://www.instagram.com/kiyanpay/"><i class="fa fa-instagram"></i></a></li> 
            </ul>
          </div>
        </div>
      </div>
</footer>

app/views/shared/_navbar.html.erb
<nav>
   <div class="navigation-wrap start-header start-style">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="navbar navbar-expand-md navbar-light">
            <%= link_to "/", class: "navbar-brand" do %>
              <%= image_tag "KP_Logo.png" %>
            <% end %>

<!--  
           To do once we add the page business -->
            <div class="pricing-container">
              <div class="pricing-switcher">
                <p class="fieldset">
                  <input type="radio" name="duration-1" value="monthly" id="monthly-1" checked>
                  <label for="monthly-1"><a href="/">Personal</a></label>
                  <input type="radio" name="duration-1" value="yearly" id="yearly-1">
                  <label for="yearly-1"><a href="/professional">Business</a></label>
                  <span class="switch"></span>
                </p>
              </div>        
            </div> 

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto py-4 py-md-0">
                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4 active">
                  <a class="nav-link" href="#"aria-expanded="false"><%= link_to"ABOUT US", about_path%></a>&nbsp &nbsp&nbsp
                  <a class="nav-link" href="#"aria-expanded="false"><%= link_to"CONTACT US", contact_path%></a>
                </li>
              </ul>

              <div class="position-btn">
                <div class='brk-btn'><a href="https://gate.kiyanpay.com/login">Log in</a></div>
              </div>
          
            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>
</nav>


<!-- Very important to make jquery work -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>